language: python
notifications:
  email:
    on_success: change
    on_failure: change

# gives us a more up-to-date glibc (required by tensorflow)
sudo: required
dist: trusty

env:
  global:
    - STATIC="false"
    - PYTHON_VERSION="3.5"
    - NENGO_DL_TEST_PRECISION="32"
    - NENGO_DL_TEST_UNROLL="False"
    - NENGO_DL_TEST_STEP_BLOCKS="None"
    - NUMPY_VERSION="numpy"
    - TF_VERSION="tensorflow"
    - NENGO_VERSION="nengo"

  matrix:
    - STATIC="true"
    - # default build
    - NENGO_DL_TEST_PRECISION="64"
    - NENGO_DL_TEST_UNROLL="True"
      NENGO_DL_TEST_STEP_BLOCKS="10"
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.4"
    - NUMPY_VERSION="numpy==1.11.0"
    - TF_VERSION="tensorflow==1.0.0"
    - NENGO_VERSION="nengo==2.3.1"

# Setup Miniconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python=$PYTHON_VERSION pip $NUMPY_VERSION
  - source activate test

# install requirements that weren't installed via conda
install:
  - pip install $TF_VERSION
  - pip install $NENGO_VERSION
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

# run pytest/flake8
script:
  - if [[ "$STATIC" == "false" ]]; then
      python setup.py develop;
      py.test --pyargs nengo --simulator nengo_deeplearning.tests.TestSimulator --ref-simulator nengo_deeplearning.tests.TestSimulator -p nengo.tests.options;
      py.test;
    else
      flake8 --ignore E721;
    fi