language: minimal
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  directories:
  - $HOME/miniconda

sudo: required
dist: trusty

env:
  global:
    - MODE="test"
    - PYTHON_VERSION="3.6"
    - NUMPY_VERSION="numpy<=1.14.5"  # TODO: remove restriction once TensorFlow is compatible with >1.14.5
    - TF_VERSION="tensorflow==1.10.0"  # TODO: test on 1.11 once travis-ci hanging issues are resolved
    - NENGO_VERSION="nengo"
    - TEST_ARGS=""

  matrix:
    - MODE="static"
    - MODE="docs"
    - # default build
    - MODE="coverage"
      NENGO_VERSION="git+https://github.com/nengo/nengo.git"
      TF_VERSION="tensorflow --pre"
    - MODE="coverage"
      NENGO_VERSION="nengo==2.7.0"
      TF_VERSION="tensorflow==1.4.0"
      PYTHON_VERSION="2.7"
    - TEST_ARGS="--dtype float64 --simulator-only"
    - TEST_ARGS="--unroll_simulation 5 --simulator-only"
    - TEST_ARGS="--inference-only --simulator-only"
    - NENGO_VERSION="git+https://github.com/nengo/nengo.git"
      TF_VERSION="tensorflow --pre"
    - NENGO_VERSION="nengo==2.7.0"
      TF_VERSION="tensorflow==1.4.0"
      NUMPY_VERSION="numpy==1.12.1"
      PYTHON_VERSION="3.4"
    - PYTHON_VERSION="2.7"

matrix:
  include:
  - language: generic  # needed for xvfb
    env: MODE="examples"

# set up miniconda
before_install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if ! [[ -d $HOME/miniconda/envs/test ]]; then
      rm -rf $HOME/miniconda;
      wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      conda create -q -y -n test python=$PYTHON_VERSION pip;
    fi
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - chmod +x .ci/*.sh

# install python requirements
install:
  - source activate test
  - export PIP_UPGRADE=true  # always upgrade to latest version
  - pip install pip
  # note: we install packages in reverse dependency order, so that we can be
  # sure we end up with the version we specify (and not the version specified
  # by a downstream dependency)
  - pip install -e .[tests]
  - .ci/$MODE.sh install
  - pip install $TF_VERSION $NENGO_VERSION $NUMPY_VERSION
  - conda list -e
  - pip freeze

before_script:
  - .ci/$MODE.sh before_script

script:
  - .ci/$MODE.sh script

after_success:
  - .ci/$MODE.sh after_success
